name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - id: webhook_fire
      if: github.event.action == 'runner_finished'
      run: echo "Event fired"

    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    # - name: Debugging with tmate
    #   uses: mxschmitt/action-tmate@v2

    # Have to do the pipenv install again because we don't know if we're on the same runner
    - name: Resource deletion script
      id: vm_create
      run: |
        pipenv install
        pipenv run python3 delete_all_resources.py "${{ github.event.client_payload.tag }}"
